version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: match_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/MatchDB
      # Other env vars
    ports:
      - "8080:8080"